import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Design system — "The Sovereign Ledger" palette (exact from stitch)
        "surface-container-lowest": "#0e0e0e",
        "surface-bright": "#393939",
        "inverse-surface": "#e5e2e1",
        "surface-variant": "#353535",
        "surface-container-high": "#2a2a2a",
        "secondary-fixed": "#ffdea7",
        "primary-container": "#d4af37",
        "on-primary-fixed-variant": "#574500",
        "inverse-primary": "#735c00",
        "secondary-container": "#765300",
        "on-primary": "#3c2f00",
        "on-tertiary-container": "#00502e",
        secondary: "#efbf68",
        "surface-tint": "#e9c349",
        "surface-container-low": "#1b1b1b",
        primary: "#f2ca50",
        "on-error": "#690005",
        "tertiary-fixed-dim": "#7fd9a2",
        "inverse-on-surface": "#313030",
        "surface-container": "#20201f",
        "on-primary-container": "#554300",
        "on-secondary-fixed-variant": "#5e4200",
        outline: "#99907c",
        "on-surface": "#e5e2e1",
        surface: "#131313",
        "on-tertiary": "#00391f",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#00522f",
        "on-background": "#e5e2e1",
        tertiary: "#87e1aa",
        "surface-container-highest": "#353535",
        error: "#ffb4ab",
        "on-primary-fixed": "#241a00",
        "error-container": "#93000a",
        "outline-variant": "#4d4635",
        "primary-fixed-dim": "#e9c349",
        "primary-fixed": "#ffe088",
        background: "#131313",
        "on-secondary": "#412d00",
        "tertiary-container": "#6bc590",
        "surface-dim": "#131313",
        "on-surface-variant": "#d0c5af",
        "secondary-fixed-dim": "#efbf68",
        "on-secondary-fixed": "#271900",
        "on-tertiary-fixed": "#002110",
        "on-secondary-container": "#faca71",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["var(--font-cinzel)", "serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
